# Generated by Django 6.0.6 on 2026-06-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_like_post', 'Can like posts'), ('can_comment_post', 'Can comment on posts')], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
